services:
  subconverter: 
    image: localhost/subconverter:latest
    hostname: subconverter
    container_name: subconverter
    volumes:
      - ./subconverter/all_base.tpl:/base/base/all_base.tpl:Z
      - ./subconverter/pref.toml:/base/pref.toml:Z
    ports:
      - "${SUBCONVERTER_HOST_PORT:-25500}:25500"

  clash-with-ui:
    image: localhost/clash-with-ui:latest
    container_name: clash-with-ui
    depends_on:
      - subconverter
    env_file:
      - .env
    ports:
      - "${ALL_PROXY_PORT:-7891}:7890"
      - "${CONTROL_PANEL_PORT:-9099}:9090"

